### PR TITLE
Correct crc-catalog version

### PR DESCRIPTION
**Pull request by striezel**
This crate says it works with crc-catalog 1.0.0, but it can't:

```
   Compiling crc v2.0.0-rc.1 (/opt/crc-rs)
error[E0310]: the parameter type `W` may not live long enough
  --> src/lib.rs:42:20
   |
41 | pub struct Crc<W: Width> {
   |                -- help: consider adding an explicit lifetime bound...: `W: 'static +`
42 |     pub algorithm: &'static Algorithm<W>,
   |                    ^^^^^^^^^^^^^^^^^^^^^ ...so that the reference type `&'static crc_catalog::Algorithm<W>` does not outlive the data it points at

error: aborting due to previous error

For more information about this error, try `rustc --explain E0310`.
error: could not compile `crc`

To learn more, run the command again with --verbose.
```
This matters when using `-Z minimal-versions` cargo option.

### CODE REVIEW

**Review by akhilles — APPROVED** [review]

File: Cargo.toml [hunk 1]
```diff
@@ -12,7 +12,7 @@ categories = ["algorithms", "no-std"]
 edition = "2018"
 
 [dependencies]
-crc-catalog = "1"
+crc-catalog = "1.1"
```
Comment (akhilles) [inline Cargo.toml:15]: Should this be a carer requirement?
```suggestion
crc-catalog = "^1.1"
```

Comment (striezel) [reply Cargo.toml:15]: Any requirement without an operator is a caret requirement by default: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio So this is already a caret requirement. :)

**Comment by akhilles** [comment]
@mrhooray I think it's safe to publish 2.0.0. The release candidate hasn't thrown any red flags so far.
