### ISSUE TITLE
Bench testing no longer working in Rust 1.26 stable

### ISSUE THREAD

**Issue by CLomanno** [mrhooray/crc-rs#34]
Code throws an error at `benches\bench.rs` at line 1:
https://github.com/mrhooray/crc-rs/blob/322576dae7da9a5beec5f45b2f2c8ad694b4febd/benches/bench.rs#L1

Rust error:
`error[E0554]: #![feature] may not be used on the stable release channel`

**Comment by mrhooray** [comment]
@CLomanno if i'm not mistaken, bencher was never in stable.
see https://doc.rust-lang.org/1.26.0/test/struct.Bencher.html

**Comment by CLomanno** [comment]
Are you planning on keeping the code in `benches/bench.rs` or removing it going forward?  In it's current state, it's broken.
